/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.view;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.model.NhanVien;
import main.service.NhanVienRepository;
//import main.service.NhanVienService;

/**
 *
 * @author ADMIN
 */
public class QuanLyNhanVien extends javax.swing.JFrame {
    
    private DefaultTableModel defaulttablemodel;
    
    private List<NhanVien> listView;
    
//    private NhanVienService service = new NhanVienService();
    private NhanVienRepository repo= new NhanVienRepository();
    /**
     * Creates new form QUANLYNHANVIEN
     */
    public QuanLyNhanVien() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
//        listView= service.getData();
          this.listView= repo.getData();
        
        this.filltable(listView);

    }
    public void filltable(List<NhanVien> list){
        this.defaulttablemodel= (DefaultTableModel) tblDanhsachnhanvien.getModel();
        this.defaulttablemodel.setRowCount(0);
        for(NhanVien nhanvien: list){
            defaulttablemodel.addRow(nhanvien.toRowTable());
        }
    }
//    public void filltabletoform(int index){
//        
//        NhanVien nhanvien= listView.get(index);
////        NhanVien nhanvien= repo.getSinhVienbyMa(index);
//       this.txtMa.setText(String.valueOf(nhanvien.getMa()));
//        this.txtHoten.setText(String.valueOf(nhanvien.getHoten()));
//        this.txtMatKhau.setText(String.valueOf(nhanvien.getMatkhau()));
//        this.cboVaitro.setSelectedIndex(nhanvien.getVaitro()?0:1);
//        
//    }
    public void fillTableToForm(int index){
//        NhanVien nhanVien = listView.get(index);
        NhanVien nhanVien = repo.getNhanVienByMa(index);
        txtMa.setText(String.valueOf(nhanVien.getMa()));
        txtHoten.setText(String.valueOf(nhanVien.getHoten()));
        txtMatKhau.setText(String.valueOf(nhanVien.getMatkhau()));
        cboVaitro.setSelectedIndex(nhanVien.getVaitro() ? 0 : 1);
    }

    public NhanVien getdatatoform(){
        String ma= this.txtMa.getText();
        String hoten= this.txtHoten.getText();
        String mk= this.txtMatKhau.getText();
        String vaiTro= (String )this.cboVaitro.getSelectedItem();
        Boolean vaitro= vaiTro.equalsIgnoreCase("Quản Lý");
        NhanVien nhanvien= new NhanVien(ma, hoten, mk,vaitro);
        return nhanvien;
    }
    public void clearform(){
        this.txtMa.setText("");
        this.txtHoten.setText("");
        this.txtMatKhau.setText("");
        this.cboVaitro.setSelectedIndex(0);
    }
    public void search(List<NhanVien> list){
        String searchma= txtTimKiem.getText();
        for(NhanVien nv: list){
            if(searchma.equalsIgnoreCase(nv.getMa())){
//             String ma = this.tblDanhsachnhanvien.getValueAt(index, 0).toString();
            int maSinhVien = Integer.valueOf(nv.getMa()); 
            this.fillTableToForm(maSinhVien);
            
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhsachnhanvien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboVaitro = new javax.swing.JComboBox<>();
        txtMa = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        btnTim = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDanhsachnhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã ", "Họ Tên", "Mật Khẩu ", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhsachnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhsachnhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhsachnhanvien);

        jLabel1.setText("Ma");

        jLabel2.setText("Hoten");

        jLabel3.setText("MatKhau");

        jLabel4.setText("Vaitro");

        cboVaitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Lý", "Nhân Viên" }));
        cboVaitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboVaitroActionPerformed(evt);
            }
        });

        btnThem.setText("THEM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SUA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XOA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel5.setText("TimKiem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnThem)
                        .addGap(34, 34, 34)
                        .addComponent(btnSua)
                        .addGap(38, 38, 38)
                        .addComponent(btnXoa)
                        .addGap(67, 67, 67)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(btnTim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboVaitro, 0, 494, Short.MAX_VALUE)
                            .addComponent(txtMa)
                            .addComponent(txtHoten)
                            .addComponent(txtMatKhau)
                            .addComponent(txtTimKiem))))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboVaitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnClear)
                    .addComponent(btnTim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhsachnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhsachnhanvienMouseClicked
        // TODO add your handling code here:
//        int index= this.tblDanhsachnhanvien.getSelectedRow();
//        
//
//        String ma= this.tblDanhsachnhanvien.getValueAt(index , 0).toString();
//        
//        int maSinhVien = Integer.valueOf(ma);
//        
//
//        System.out.println(ma);
//
//        this.filltabletoform(maSinhVien);


            
         int index = this.tblDanhsachnhanvien.getSelectedRow();
//        this.fillTableToForm(index);
        
        String ma = this.tblDanhsachnhanvien.getValueAt(index, 0).toString();
        int maSinhVien = Integer.valueOf(ma);
        System.out.println(ma);
        this.fillTableToForm(maSinhVien);
    }//GEN-LAST:event_tblDanhsachnhanvienMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.clearform();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String VaiTro = (String ) cboVaitro.getSelectedItem();
        this.repo.add(getdatatoform());
        this.listView.clear();
        this.repo.getData();
        this.filltable(listView);
        JOptionPane.showMessageDialog(this, "Them thanh cong!");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int index= this.tblDanhsachnhanvien.getSelectedRow();
        String ma= this.tblDanhsachnhanvien.getValueAt(index, 0).toString();
        int masinhvien= Integer.valueOf(ma);
        this.repo.delete(masinhvien);
        this.listView.clear();
        this.filltable(listView);
        JOptionPane.showMessageDialog(this, "Xoa thanh cong!");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int index= this.tblDanhsachnhanvien.getSelectedRow();
        String ma= this.tblDanhsachnhanvien.getValueAt(index, 0).toString();
        
        
        int manhanvien= Integer.valueOf(ma);
//        
        this.repo.capnhat(manhanvien, this.getdatatoform());
        this.listView.clear();
        this.filltable(listView);
        JOptionPane.showMessageDialog(this, "Sua thanh cong!");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void cboVaitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboVaitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboVaitroActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        this.search(listView);
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboVaitro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDanhsachnhanvien;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMa;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
